// Jenkinsfile CI/CD Pipeline for Test Execution
// Generated by BMad TEA Agent - Test Architect Module
// Optimized for: Parallel Sharding (by pytest marker)
// Burn-in (flaky-test detection) intentionally omitted — backend/deterministic stack.
// Stack: backend | Framework: pytest
//
// Assumptions (no .python-version / pyproject.toml pinned in repo):
//   - `python3` is available on the Jenkins agent (adjust PYTHON_BIN below if not)
//   - Dependencies come solely from requirements.txt (pip)
//   - pytest markers are declared in pytest.ini: regression, security
//
// Security notes:
//   - TEST_MARKERS is validated against an allow-list (ALLOWED_MARKERS) before
//     being turned into a `pytest -m` expression, to prevent shell/marker injection
//     via build parameters.
//   - GIT_REF is validated against a safe branch-name pattern before use.
//
// Quality gate policy:
//   - `security` marker = P0 — any failure fails the build (pytest's non-zero exit
//     already fails the shard stage; no extra gating needed at this suite size).
//   - `regression` marker = P1 (target >=95% pass rate) — currently enforced the
//     same way (any failure fails the build) since the suite is small; revisit
//     with a pass-rate threshold script if the regression suite grows large enough
//     for a small number of failures to be an acceptable trade-off.

pipeline {
    agent any

    environment {
        CI = 'true'
        PYTHON_BIN = 'python3'
    }

    parameters {
        string(name: 'MR_ID', defaultValue: '', description: 'Merge request ID (optional, for traceability)')
        string(name: 'GIT_REF', defaultValue: 'main', description: 'Branch or ref to build')
        string(name: 'TEST_MARKERS', defaultValue: 'regression,security', description: 'Comma-separated pytest markers to run (allowed: regression, security)')
        string(name: 'NOTIFY_EMAIL', defaultValue: '', description: 'Distribution list to email on failure (leave empty to disable)')
    }

    options {
        timeout(time: 45, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Validate Parameters') {
            steps {
                script {
                    if (!(params.GIT_REF ==~ /^[A-Za-z0-9_\-\/.]+$/)) {
                        error("Invalid GIT_REF: '${params.GIT_REF}'")
                    }

                    def allowedMarkers = ['regression', 'security'] as Set
                    def requested = params.TEST_MARKERS.split(',').collect { it.trim() }.findAll { it }
                    def invalid = requested.findAll { !allowedMarkers.contains(it) }
                    if (invalid) {
                        error("Unknown pytest marker(s): ${invalid.join(', ')}. Allowed: ${allowedMarkers.join(', ')}")
                    }
                    if (requested.isEmpty()) {
                        error("TEST_MARKERS must include at least one of: ${allowedMarkers.join(', ')}")
                    }

                    env.VALIDATED_MARKERS = requested.join(',')
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: params.GIT_REF,
                    url: 'https://github.com/OmarMeejri/LLMTester.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install') {
            steps {
                sh '''
                    "$PYTHON_BIN" -m venv .venv
                    . .venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install pytest-xdist pytest-cov ruff
                '''
                // No stash/unstash: the whole pipeline runs on one `agent any` workspace,
                // so .venv is already on disk for every later stage. Stashing it tripped
                // Jenkins' tar-symlink guard on venv's lib64 -> lib symlink.
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    . .venv/bin/activate
                    ruff check --select=E9,F .
                ''' // Scoped to real errors (syntax/undefined names) since the repo has no
                    // prior lint config; the full default ruleset flags pre-existing,
                    // harmless style issues that would fail the very first CI run
            }
        }

        // Test stage - parallel shards, one per validated pytest marker
        stage('Test') {
            parallel {
                stage('Shard - Regression') {
                    when {
                        expression { env.VALIDATED_MARKERS.split(',').contains('regression') }
                    }
                    steps {
                        sh '''
                            . .venv/bin/activate
                            pytest -m regression -n auto --cov=. --cov-report=xml:coverage-regression.xml --junitxml=results-regression.xml
                        '''
                    }
                }
                stage('Shard - Security') {
                    when {
                        expression { env.VALIDATED_MARKERS.split(',').contains('security') }
                    }
                    steps {
                        sh '''
                            . .venv/bin/activate
                            pytest -m security -n auto --cov=. --cov-report=xml:coverage-security.xml --junitxml=results-security.xml
                        '''
                    }
                }
            }
        }

        // Burn-In stage intentionally omitted: backend-only stack with deterministic
        // unit/API tests (no UI flakiness). Re-add if flaky tests start appearing:
        // stage('Burn-In') { steps { for i in 1..10: pytest -m "$MARKER_EXPR" } }
    }

    post {
        always {
            // Archive test results and coverage reports
            archiveArtifacts artifacts: 'results-*.xml,coverage-*.xml', allowEmptyArchive: true
            junit testResults: 'results-*.xml', allowEmptyResults: true
        }
        failure {
            echo 'Pipeline failed - check test results and artifacts'
            script {
                if (params.NOTIFY_EMAIL?.trim()) {
                    mail to: params.NOTIFY_EMAIL,
                        subject: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                        body: "Build failed: ${env.BUILD_URL}\nArtifacts: ${env.BUILD_URL}artifact/"
                }
            }
        }
    }
}
